POST http://localhost:5178/register
Content-Type: application/json

{
    "Email": "mostafa.azouz@gmail.com",
    "Password": "Squash17_!"
}


###

POST http://localhost:5178/forgotPassword
Content-Type: application/json

{
    "Email": "mostafa.azouz@gmail.com"
}
###

POST http://localhost:5178/confirmEmail
Content-Type: application/json

{
    "Email": "mostafa.azouz@gmail.com"
}

###
GET http://localhost:5178/user


###

Delete http://localhost:5178/user/Delete/9515ff02-1ed2-4c61-b3be-1b7b78ea6ffc

