POST http://localhost:5178/register
Content-Type: application/json

{
    "Email": "mostafa.azouz@gmail.com",
    "Password": "Squash17_!"
}


###

POST http://localhost:5178/forgotPassword
Content-Type: application/json

{
    "Email": "mostafa.azouz@gmail.com"
}
###

POST http://localhost:5178/confirmEmail
Content-Type: application/json

{
    "Email": "mostafa.azouz@gmail.com"
}

###
GET http://localhost:5178/user


###

Delete http://localhost:5178/user/Delete/89814fe8-d72e-42eb-a616-29b1a4937114

